name: mbedtls

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  ffi: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  ffigen:
    path: '../native/pkgs/ffigen'
  lints: ^2.0.1

ffigen:
  name: mbedtls
  ffi-native:
    assetId: 'c { vcpkg="mbedtls" }'
  description: Bindings to `mbedtls.h`.
  output: 'mbedtls/generated.kk'
  compiler-opts:
    - '-Ideps/mbedtls/include'
    - '-I/usr/local/opt/llvm/lib/clang/18/include'
  headers:
    entry-points:
      - 'deps/mbedtls/include/mbedtls/*.h'
    include-directives:
      - '**/mbedtls/*.h'
      - '**/psa/*.h'
  compiler-opts-automatic:
    macos:
      include-c-standard-library: false
  preamble: |
    // Copyright (c) 2020, the Koka-Community authors. All rights reserved. 
    // Use of this source code is governed by a
    // MIT-style license that can be found in the LICENSE file.
  functions:
    exclude:
      - (-)+.*
  structs:
    exclude:
      - (-)+.*
    member-rename:
      '.*':
        '-(.*)': '$1'
    dependency-only: opaque
  enums:
    exclude:
      - (-)+.*
  unions:
    exclude:
      - (-)+.*
  globals:
    exclude:
      - (-)+.*
  macros:
    exclude:
      - (-)+.*
  typedefs:
    exclude:
      - (-)+.*
